ALTER TABLE "session_metrics"
    ADD COLUMN IF NOT EXISTS "frames_captured" integer DEFAULT 0,
    ADD COLUMN IF NOT EXISTS "frames_skipped_duplicate" integer DEFAULT 0,
    ADD COLUMN IF NOT EXISTS "frames_skipped_throttle" integer DEFAULT 0,
    ADD COLUMN IF NOT EXISTS "frames_skipped_backlog" integer DEFAULT 0,
    ADD COLUMN IF NOT EXISTS "frames_skipped_map_moving" integer DEFAULT 0,
    ADD COLUMN IF NOT EXISTS "battery_level_percent" integer,
    ADD COLUMN IF NOT EXISTS "battery_state" varchar(20),
    ADD COLUMN IF NOT EXISTS "low_power_mode_enabled" boolean,
    ADD COLUMN IF NOT EXISTS "battery_level_start_percent" integer,
    ADD COLUMN IF NOT EXISTS "battery_level_end_percent" integer,
    ADD COLUMN IF NOT EXISTS "battery_delta_percent" integer,
    ADD COLUMN IF NOT EXISTS "battery_state_start" varchar(20),
    ADD COLUMN IF NOT EXISTS "battery_state_end" varchar(20),
    ADD COLUMN IF NOT EXISTS "charging_state_changed" boolean,
    ADD COLUMN IF NOT EXISTS "low_power_mode_observed" boolean,
    ADD COLUMN IF NOT EXISTS "thermal_state_start" varchar(20),
    ADD COLUMN IF NOT EXISTS "thermal_state_peak" varchar(20),
    ADD COLUMN IF NOT EXISTS "thermal_state_end" varchar(20),
    ADD COLUMN IF NOT EXISTS "thermal_throttled_duration_ms" bigint,
    ADD COLUMN IF NOT EXISTS "memory_pressure_peak" varchar(20),
    ADD COLUMN IF NOT EXISTS "memory_pressure_event_count" integer,
    ADD COLUMN IF NOT EXISTS "memory_headroom_mb_bucket_start" integer,
    ADD COLUMN IF NOT EXISTS "memory_headroom_mb_bucket_min" integer,
    ADD COLUMN IF NOT EXISTS "memory_headroom_mb_bucket_end" integer,
    ADD COLUMN IF NOT EXISTS "font_scale_bucket" varchar(20),
    ADD COLUMN IF NOT EXISTS "ui_style" varchar(20),
    ADD COLUMN IF NOT EXISTS "layout_direction" varchar(10),
    ADD COLUMN IF NOT EXISTS "orientation_start" varchar(20),
    ADD COLUMN IF NOT EXISTS "orientation_end" varchar(20),
    ADD COLUMN IF NOT EXISTS "orientation_change_count" integer,
    ADD COLUMN IF NOT EXISTS "display_max_refresh_rate_hz" integer;
